<!-- footer div -->
<div class="clear"></div>

<div class="footer">
<div class="container-fluid">
<hr>
<span class="text-muted">| IssueTracker | Copyright &copy; 2014 | Daniel Mayoss |</span>
</div>
</div>

<!-- loading javascript here so pages load faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>

</html>

